FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
RUN apt-get update -y && \
    apt-get upgrade -y && \
    npm install -g npm@latest && \
    npm install -g pnpm@latest @antfu/ni
    
