import type { Metadata } from "next";

import { GlobalSingleType } from "@/gql/global/global.interface";
import { globalQuery } from "@/gql/global/global.query";
import { graphqlRequest } from "@/gql/graphql-request";

import { HeaderComponent } from "@/components/layout/header.component";

import "./globals.css";
import { FooterComponent } from "@/components/layout/footer.component";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let global: GlobalSingleType;
  try {
    const { global: globalData } = await graphqlRequest<{
      global: GlobalSingleType;
    }>(globalQuery);

    global = globalData;

    if (global == null) {
      notFound();
    }
  } catch (_error) {
    notFound();
  }

  return (
    <html lang="en">
      <body className="mx-auto max-w-7xl">
        <HeaderComponent {...global.header} />
        {children}
        <FooterComponent {...global.footer} />
      </body>
    </html>
  );
}
