import type { Metadata } from "next";

import { GlobalSingleType } from "@/gql/global/global.interface";
import { graphqlRequest } from "@/gql/graphql-request";
import { globalQuery } from "@/gql/global/global.query";

import { HeaderComponent } from "@/components/layout/header.component";
import { FooterComponent } from "@/components/layout/footer.component";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { global } = await graphqlRequest<{
    global: GlobalSingleType;
  }>(globalQuery);

  return (
    <html lang="en">
      <body className="mx-auto max-w-7xl">
        <HeaderComponent {...global.header} />
        {children}
        <FooterComponent {...global.footer} />
      </body>
    </html>
  );
}
